create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  constraint newsletter_subscribers_email_length check (char_length(email) between 3 and 320)
);

alter table public.newsletter_subscribers enable row level security;

drop policy if exists "Public can subscribe to newsletter" on public.newsletter_subscribers;
create policy "Public can subscribe to newsletter"
  on public.newsletter_subscribers
  for insert
  to anon, authenticated
  with check (true);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  total_amount integer not null check (total_amount > 0),
  status text not null default 'requested' check (status in ('requested', 'confirmed', 'paid', 'processing', 'completed', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.orders enable row level security;

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
  on public.orders
  for insert
  to anon, authenticated
  with check (true);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_name text not null,
  unit_price integer not null check (unit_price > 0),
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.order_items enable row level security;

drop policy if exists "Public can create order items" on public.order_items;
create policy "Public can create order items"
  on public.order_items
  for insert
  to anon, authenticated
  with check (true);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "Admins can view admin membership" on public.admin_users;
create policy "Admins can view admin membership"
  on public.admin_users
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view orders" on public.orders;
create policy "Admins can view orders"
  on public.orders
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders"
  on public.orders
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can view order items" on public.order_items;
create policy "Admins can view order items"
  on public.order_items
  for select
  to authenticated
  using (public.is_admin());

