create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  constraint newsletter_subscribers_email_length check (char_length(email) between 3 and 320)
);

alter table public.newsletter_subscribers enable row level security;

drop policy if exists "Public can subscribe to newsletter" on public.newsletter_subscribers;
create policy "Public can subscribe to newsletter"
  on public.newsletter_subscribers
  for insert
  to anon, authenticated
  with check (true);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  total_amount integer not null check (total_amount > 0),
  status text not null default 'requested' check (status in ('requested', 'confirmed', 'paid', 'processing', 'completed', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.orders enable row level security;

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
  on public.orders
  for insert
  to anon, authenticated
  with check (true);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_name text not null,
  unit_price integer not null check (unit_price > 0),
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.order_items enable row level security;

drop policy if exists "Public can create order items" on public.order_items;
create policy "Public can create order items"
  on public.order_items
  for insert
  to anon, authenticated
  with check (true);

